
stacking:
 lgbm_param:
  objective: "binary"
  metric: "auc"
  verbosity: -1
  learning_rate: 0.1
move_average:
 lgbm_param:
  objective: "binary"
  metric: "auc"
  verbosity: -1
  learning_rate: 0.1
ohlc:
 lgbm_param:
  objective: "binary"
  metric: "auc"
  verbosity: -1
  learning_rate: 0.1
bollinger_band:
 lgbm_param:
  objective: "binary"
  metric: "auc"
  verbosity: -1
  learning_rate: 0.1
stochastics:
 lgbm_param:
  objective: "binary"
  metric: "auc"
  verbosity: -1
  learning_rate: 0.1
correlation:
 lgbm_param:
  objective: "binary"
  metric: "auc"
  verbosity: -1
  learning_rate: 0.1