name: ml-deploy
on:
 push:
   branches:
     - fix/workflow

jobs:
 build:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout
       uses: actions/checkout@v2
     
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

     - name: make credentials file
       run: |
        mkdir ~/.aws
        touch ~/.aws/credentials
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
        echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

     - name: compose-run
       env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-2
       run: |
        docker-compose up --build
        docker tag stockscope_ml-container:latest 835636182609.dkr.ecr.us-east-2.amazonaws.com/learning:latest
        #aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 835636182609.dkr.ecr.us-east-2.amazonaws.com
        #docker push 835636182609.dkr.ecr.us-east-2.amazonaws.com/learning:latest